copyright: GL513 Github Page
site_name: GL513 Github 
site_url: https://GL513.github.io/
site_description: GL513 Github. 
extra:
  disqus: gl513
theme:
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
  font:
    text: Inconsolata
  name: material
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - toc:
      permalink: »
extra:
 analytics:
    provider: google
    property: G-XXXXXXXXXX
 social:
  - icon: fontawesome/brands/github
    link: https://github.com/gl513
    name: GL513 Github
